fixtures:
  forge_modules:
    concat: 
      repo: 'puppetlabs/concat'
      ref: '1.0.2'
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    ssh: "#{source_dir}"
